### ISSUE TITLE
SOLID

### ISSUE THREAD

**Issue by chrisharrison** [jawira/case-converter#40]
I can't easily inject the functionality this package provides as a dependency to one of my classes because I have to create a new instance every time I want to perform a conversion. This breaks the inversion of control principle of SOLID.

To use this properly I'd have to make a factory and inject it everywhere which is definitely sub-optimal.

**Comment by jawira** [comment]
To use `case-converter` you have to pass the input string when instantiating `Convert` class, there's no other way. The idea behind this was to have an immutable object, once created you cannot change the input string.

Also, `Convert` class is supposed to be very simple to use: you instantiate the class, and then you call the "`->to*()`" methods. That's it.

Do you have any suggestion to improve this? If so it could be added in v4 of `case-converter`.

**Comment by chrisharrison** [comment]
https://github.com/chrisharrison/case-converter/tree/master

**Comment by jawira** [comment]
Ok, that's what I call a suggestion! I'm going to implement a small factory class.

**Comment by jawira** [comment]
Hello @chrisharrison , can you take a look at  https://github.com/jawira/case-converter/pull/47

**Comment by jawira** [comment]
Nice! thanks for your help @chrisharrison
